### ISSUE TITLE
kvm-ioctls 0.4.0

### ISSUE THREAD

**Issue by sameo** [rust-vmm/kvm#59]
With cloud-hypervisor we're using the GSI routing ioctl (commit 37669f60). Since we've also added support `unregister_irqfd` since 0.2.0, and there are no pending new features, should we do a 0.3.0 release?

**Comment by sameo** [comment]
cc @andreeaflorescu

**Comment by andreeaflorescu** [comment]
Yap, I was planning on doing that. For this release I would also like to update kvm-ioctls to use vmm-sys-util. I'll do that these days.

**Comment by sameo** [comment]
I'd also suggest you add the rust-vmm gatekeepers team to the crate owners, so that we can help with the publishing part.

**Comment by andreeaflorescu** [comment]
Yap, will do. @acatangiu will help with the necessary changes.

**Comment by jiangliu** [comment]
I still have one small PR for 0.3.0 version, will post it soon:)

**Comment by andreeaflorescu** [comment]
Since vmm-sys-util is now available, we should also fix the following issues before publishing on crates.io:

- [x] use errno from vmm-sys-util instead of std::io::error: https://github.com/rust-vmm/kvm-ioctls/issues/35
- [x] remove ioctls.rs: https://github.com/rust-vmm/kvm-ioctls/issues/23
- [x] fix export of cpuid related consts: https://github.com/rust-vmm/kvm-ioctls/issues/16
- [x] use Eventfd instead of RawFds so that we don't have to have unsafe functions: https://github.com/rust-vmm/kvm-ioctls/issues/39
- [x] Use `FamStructWrapper` from vmm-sys-util: https://github.com/rust-vmm/kvm-ioctls/pull/58

**Comment by andreeaflorescu** [comment]
We published 0.3.0, let's do the remaining items for our next release.
