### ISSUE TITLE
Publish kvm-ioctls v0.1.0 to crates.io

### ISSUE THREAD

**Issue by andreeaflorescu** [rust-vmm/kvm#7]
- [x] Update README.md with high level documentation and usage: https://github.com/rust-vmm/kvm-ioctls/issues/25
- [x] Setup CI - <s>Pending decision for regarding the CI to use. Current options: Buildkite & Jenkins</s> Buildkite is running the CI.
- [x] Update public function documentation with examples - PR #13 
- [x] Update license as per discussion in https://github.com/rust-vmm/community/issues/14
